#!/usr/bin/env python3
from lib import speak, recognize
from lib import Switchboard
import sys, subprocess

def main():

    def echo(*args):
        speak(' '.join(args))

    def scour(*args):
        subprocess.call(['scour'] + list(args))

    functions = {
            'echo'  : echo,
            'scour' : scour
            }

    sb = Switchboard(functions)
    sb.loop()
    return 0

if __name__ == '__main__':
    sys.exit(main())
